name: deforestation-alerts-module
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - cartopy>=0.24.0
  - fiona>=1.10
  - gdal>=3.8
  - geemap>=0.35.0
  - geopandas>=1.0
  - ipyevents>=2.0
  - ipyleaflet>=0.19
  - ipython>=8.12
  - ipyvuetify>=1.10.0
  - ipywidgets>=8.1
  - matplotlib>=3.9
  - numpy>=1.26,<2
  - pandas>=2.2
  - pyproj
  - rasterio>=1.3
  - shapely>=2.0
  - tensorflow>=2.16,<2.18
  - tensorflow-probability>=0.24
  - tf-keras
  - traitlets>=5.14
  - pip
  - pip:
      - dateutils==0.6.12
      - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
      - geedim==1.8.1
      - huggingface_hub
      - matplotlib-scalebar==0.8.1
      - MightyMosaic==1.2.3
      - python-docx==1.1.2
      - sepal_ui==2.22.1
      - tomli==2.0.2
      - voila==0.5.8
      - pygaul<=4
