from sepal_ui import model
from traitlets import Any, Int, Float

from component import parameter as cp
from component.message import cm


class AlertAnalysisModel(model.Model):

    ############################################################################
    # selected alerts
    ############################################################################
    alerts_gdf = Any(None).tag(sync=True)
    "Geodataframe containing centroids of alerts to be reviewed"

    actual_alert_id = Int(-1).tag(sync=True)
    "ID of current alert being reviewed"

    max_alert_id = Int(-1).tag(sync=True)
    "ID of last alert"

    before_planet_monthly_images = Any(None).tag(sync=True)
    "List of available before images from planet monthly, just for current alert"

    after_planet_monthly_images = Any(None).tag(sync=True)
    "List of available after images from planet monthly, just for current alert"

    before_s2_images = Any(None).tag(sync=True)
    "List of available before images from sentinel 2, just for current alert"

    before_s2_images_time = Float(None).tag(sync=True)
    "Time when before images from sentinel 2 were set"

    after_s2_images = Any(None).tag(sync=True)
    "List of available after images from sentinel 2, just for current alert"

    after_s2_images_time = Float(None).tag(sync=True)
    "Time when after images from sentinel 2 were set"

    before_landsat_images = Any(None).tag(sync=True)
    "List of available before images from landsat, just for current alert"

    before_landsat_images_time = Float(None).tag(sync=True)
    "Time when before images from landsat were set"

    after_landsat_images = Any(None).tag(sync=True)
    "List of available after images from landsat, just for current alert"

    after_landsat_images_time = Float(None).tag(sync=True)
    "Time when after images from landsat were set"

    before_img = Any(None).tag(sync=True)
    "Path to downloaded before img"

    after_img = Any(None).tag(sync=True)
    "Path to downloaded after img"

    model1_prediction_file = Any(None).tag(sync=True)
    "Alert polygons generated with DL model"

    model2_prediction_file = Any(None).tag(sync=True)
    "Alert polygons generated with DL model"

    model1_prediction_time = Int(None).tag(sync=True)
    "Time when alert polygons m1 were generated"

    model2_prediction_time = Int(None).tag(sync=True)
    "Time when alert polygons m2 were generated"

    defo_dl_layer = Any(None).tag(sync=True)
    "Alert polygons generated by the user"

    alert_report = Any(None).tag(sync=True)
    "Path to reach pdf/word report file generated"

    def export_dictionary(self):
        dictionary = {
            "actual_alert_id": (
                0 if self.actual_alert_id == -1 else self.actual_alert_id
            ),
            "max_alert_id": 0 if self.actual_alert_id == -1 else self.actual_alert_id,
        }
        return dictionary

    def import_from_dictionary(self, data):
        import json

        """
        Import class attributes from a JSON file.
        Args:
            data (str): Dcitionary JSON file.
        """
        try:
            # Update attributes
            self.actual_alert_id = data.get("actual_alert_id", self.actual_alert_id)
            self.max_alert_id = data.get("max_alert_id", self.max_alert_id)
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"Error loading JSON file: {e}")

    def reset_model(self):
        self.alerts_gdf = None
        self.actual_alert_id = -1
        self.max_alert_id = -1
        self.before_planet_monthly_images = None
        self.after_planet_monthly_images = None
        self.before_s2_images = None
        self.before_s2_images_time = None
        self.after_s2_images = None
        self.after_s2_images_time = None
        self.before_landsat_images = None
        self.before_landsat_images_time = None
        self.after_landsat_images = None
        self.after_landsat_images_time = None
        self.before_img = None
        self.after_img = None
        self.model1_prediction_file = None
        self.model1_prediction_file = None
        self.model1_prediction_time = None
        self.model1_prediction_time = None
        self.defo_dl_layer = None
        self.alert_report = None
