from sepal_ui import model
from traitlets import Any, Int, Float

from component import parameter as cp
from component.message import cm


class AlertAnalysisModel(model.Model):

    ############################################################################
    # selected alerts
    ############################################################################
    alerts_gdf = Any(None).tag(sync=True)
    "Geodataframe containing centroids of alerts to be reviewed"

    actual_alert_id = Int(-1).tag(sync=True)
    "ID of current alert being reviewed"

    before_planet_monthly_images = Any(None).tag(sync=True)
    "List of available before images from planet monthly, just for current alert"

    before_sentinel2_images = Any(None).tag(sync=True)
    "List of available before images from sentinel 2 img, just for current alert"

    before_planet_daily_images = Any(None).tag(sync=True)
    "List of available before images from planet daily, just for current alert"

    after_planet_monthly_images = Any(None).tag(sync=True)
    "List of available after images from planet monthly, just for current alert"

    after_sentinel2_images = Any(None).tag(sync=True)
    "List of available after images from sentinel 2 img, just for current alert"

    after_planet_daily_images = Any(None).tag(sync=True)
    "List of available after images from planet daily, just for current alert"

    before_img = Any(None).tag(sync=True)
    "Path to downloaded before img"

    after_img = Any(None).tag(sync=True)
    "Path to downloaded after img"

    auto_alert_polygons = Any(None).tag(sync=True)
    "Alert polygons generated with DL model"

    user_alert_polygons = Any(None).tag(sync=True)
    "Alert polygons generated by the user"

    alert_report = Any(None).tag(sync=True)
    "Path to reach pdf/word report file generated"
